### ISSUE TITLE
Make Tailor to work with immutable non-optional types

### ISSUE THREAD

**Issue by kostiakoval** [zenangst/Tailor#23]
Let's say I have an immutable model (which I do have often, and it's a good think to do :smiley:  )

```swift
struct Person {

  let firstName: String
  let lastName: String
}

let p = Person(firstName: "Sarah ", lastName: "Connor")
```
Now I want to use Tailor Mapper to map my JSON to the `Person` type

```swift
extension Person: Mappable {
  init(_ map: JSONDictionary) {
    firstName <- map.property("first_name")
    lastName  <- map.property("last_name")
  }
}

let dictionary = ["first_name" : "Sarah", "last_name" : "Connor"]
let model = Person(dictionary)
```
In that way you can first start with making models and using them directly. 
After that you can add Mapping support without breaking ability to directly instantiate your `Person` model

**Comment by zenangst** [comment]
@kostiakoval Started looking into this and then I found this thread - http://stackoverflow.com/questions/27825362/can-i-initialize-a-variable-using-a-custom-assignment-operator/27827754#27827754

Seems like we can't achieve this using `infix operators`, I'm current looking into other alternatives and nifty stuff that could potentially work.

**Comment by kostiakoval** [comment]
:tada: 
![Giphy](http://media4.giphy.com/media/lCP95tGSbMmWI/giphy.gif)
