### ISSUE TITLE
I'mma let you finish, but …

### ISSUE THREAD

**Issue by sindrenm** [zenangst/Tailor#3]
![imma-let-you-finish](https://cloud.githubusercontent.com/assets/386122/9813644/bf90a714-5887-11e5-8dad-1dbc394fa434.jpg)

**Comment by zenangst** [comment]
![46024227](https://cloud.githubusercontent.com/assets/57446/9814595/897b4514-588f-11e5-8c99-c8ed30a6686d.jpg)

**Comment by sindrenm** [comment]
**#satisfied**
