### ISSUE TITLE
Simple assignment

### ISSUE THREAD

**Issue by onmyway133** [zenangst/Tailor#41]
For now, we use `<-` which requires that the variable to be declared as `var` and has initial values, like

```swift
struct Person: Mappable {
      var name: String = ""

      init(_ map: JSONDictionary) {
        self.name <- map.path(["info"])?.property("name")
      }
}
```

How about having something like `parse` with `DefaultType` protocol, so that correct or default value is returned. `parse` will unwrap optional or return default value. It can be written as postfix operator

```swift
struct Person: Mappable {
      let name: String // 😬

      init(_ map: JSONDictionary) {
        self.name = parse(map.path(["info"])?.property("name"))
      }
}
```

**Comment by onmyway133** [comment]
@zenangst something like this https://github.com/zenangst/Tailor/pull/42 😬

**Comment by zenangst** [comment]
@onmyway133 should I just close this? 😁

**Comment by onmyway133** [comment]
@zenangst yeah, it should be closed
