### ISSUE TITLE
Getting error when using JSONDictionary

### ISSUE THREAD

**Issue by salimgcet** [zenangst/Tailor#57]
Hello Team,

I am using Tailor for parsing the JSON.

I am getting very wiered error "Use of Undecleared type of 'JSONDictionary'  "

**Comment by zenangst** [comment]
Hey @salimgcet, it seems like the `README` was a bit outdated. `JSONDictionary` was a type alias that came from `Sugar` (a previous dependency). `Tailor` no longer depends on `Sugar` so instead of using `JSONDictionary`, you can just use `[String : Any]`.

**Comment by zenangst** [comment]
I'm gonna go ahead and close this one but feel free to re-open it if this is still causing issues for you somehow.
